### ISSUE TITLE
Error when trying to create conda env 

### ISSUE THREAD

**Issue by MyJumperBroke23** [elicassion/sugarl#2]
When conda create the env off of the yaml file, I get the following error:

Installing pip dependencies: \ Ran pip subprocess with arguments:
['/work/ahsia/anaconda3/envs/arl/bin/python', '-m', 'pip', 'install', '-U', '-r', '/work/ahsia/autoexperiment_dataset/2306.00975/sugarl/condaenv.38az271m.requirements.txt', '--exists-action=b']
Pip subprocess output:
Collecting git+https://github.com/elicassion/active-gym.git (from -r /work/ahsia/autoexperiment_dataset/2306.00975/sugarl/condaenv.38az271m.requirements.txt (line 25))
  Cloning https://github.com/elicassion/active-gym.git to /tmp/pip-req-build-3nih0pn0
  Resolved https://github.com/elicassion/active-gym.git to commit 6fe4b609730873a416dab1822a07c8638f61c656
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  Running command git clone --filter=blob:none --quiet https://github.com/elicassion/active-gym.git /tmp/pip-req-build-3nih0pn0
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in active_gym setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed

**Comment by elicassion** [comment]
Hi @MyJumperBroke23 ,

Thanks for letting me know the bug! It is caused by inappropriate string format in `extras_require` for `rlbench` in `setup.py` in `active_gym`. 

I have already fixed it by https://github.com/elicassion/active-gym/commit/573cb60dd972eb55e9050ce701952be6463a26c0. Now the conda env creation should work. I tested on my end.

Best,

**Comment by MyJumperBroke23** [comment]
That fixed it, thanks so much!
