### ISSUE TITLE
AttributeError: 'MjModel' object has no attribute 'bvh_geomid'

### ISSUE THREAD

**Issue by MyJumperBroke23** [elicassion/sugarl#3]
Hi,

I'm trying to run the dmc_20 training script, but when I do, I get the following error:

```
AttributeError: 'MjModel' object has no attribute 'bvh_geomid'
```

**Comment by elicassion** [comment]
Hi @MyJumperBroke23 ,

I guess we can install `mujoco` `2.x` versions insteal of `3.x`. I will verify this solution later when I am available.

**Comment by elicassion** [comment]
Installing `mujoco<3.0` will solve the problem. I have also updated the conda env file. See https://github.com/elicassion/sugarl/commit/77a7fb10c997e47b34e6802cea0501d2b87505f1
